"""
report.py
==========
Generates professional scan reports in TXT, XML, JSON, HTML, and PDF
formats from a ScanResult (see scanner.py). Each report includes
target, timing, the command executed, parsed port/service/OS data,
NSE results, banner information, and general recommendations.
"""

from __future__ import annotations

import html
import json
import xml.etree.ElementTree as ET
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Dict, List, Optional

from config import APP_NAME, APP_VERSION, REPORTS_DIR
from scanner import ScanResult
from utils import (
    default_report_filename, ensure_directory, human_timestamp, sanitize_filename,
)


@dataclass
class ReportData:
    """Normalized data model shared by every report format."""
    target: str
    date: str
    duration: str
    command: str
    open_ports: List[Dict] = field(default_factory=list)
    closed_ports_summary: str = ""
    filtered_ports_summary: str = ""
    services: List[Dict] = field(default_factory=list)
    os_guess: str = ""
    nse_results: str = ""
    banners: List[Dict] = field(default_factory=list)
    recommendations: List[str] = field(default_factory=list)
    raw_output: str = ""


@dataclass
class ReportSection:
    """One task's contribution to an aggregated multi-task report."""
    index: int
    label: str
    status: str
    command: str
    duration: str
    output: str
    error: str = ""
    banners: List[Dict] = field(default_factory=list)


@dataclass
class AggregatedReportData:
    """Report model for a multi-task ScanJob (see job.py)."""
    target: str
    scan_started: str
    scan_finished: str
    duration: str
    sections: List[ReportSection] = field(default_factory=list)
    notes: List[str] = field(default_factory=list)
    summary: Dict[str, int] = field(default_factory=dict)


def build_job_report_data(job, notes: Optional[List[str]] = None) -> "AggregatedReportData":
    """
    Build an AggregatedReportData from a completed job.ScanJob. Kept
    free of a hard import of job.py's types to avoid a circular import
    (job.py does not import report.py); `job` is duck-typed here.
    """
    sections = [
        ReportSection(
            index=i + 1,
            label=task.label,
            status=task.status.value if hasattr(task.status, "value") else str(task.status),
            command=task.command or " ".join(task.args),
            duration=f"{task.duration_seconds:.2f}s" if task.duration_seconds else "-",
            output=task.stdout,
            error=task.stderr,
            banners=list(getattr(task, "banners", []) or []),
        )
        for i, task in enumerate(job.tasks)
    ]
    return AggregatedReportData(
        target=job.target,
        scan_started=job.started_at,
        scan_finished=job.ended_at,
        duration=f"{job.duration_seconds:.2f}s",
        sections=sections,
        notes=notes or [],
        summary=job.summary_counts(),
    )


def generate_aggregated_txt(data: AggregatedReportData, filepath: Path) -> Path:
    lines = [
        f"{APP_NAME} Report", "=" * 50,
        f"Target          : {data.target}",
        f"Scan Started    : {data.scan_started}",
        f"Scan Finished   : {data.scan_finished}",
        f"Duration        : {data.duration}", "",
    ]
    for s in data.sections:
        lines += [f"[{s.index}] {s.label} — {s.status}", "-" * 50,
                   f"Command  : {s.command}", f"Duration : {s.duration}"]
        if s.error:
            lines.append(f"Error    : {s.error}")
        lines += ["Output:", s.output or "(no output)"]
        if s.banners:
            lines += ["", "Banner Information:"]
            for b in s.banners:
                reach = "reachable" if b.get("reachable") else "unreachable"
                lines.append(f"  Port {b.get('port')} [{reach}]: {b.get('banner') or '(no banner)'}")
        lines.append("")

    if data.notes:
        lines += ["Notes", "-" * 50] + [f"  - {n}" for n in data.notes] + [""]

    lines += ["Summary", "-" * 50]
    for status, count in data.summary.items():
        lines.append(f"  {status.title()}: {count}")
    lines += ["", "-" * 50, f"Generated by {APP_NAME} v{APP_VERSION}"]

    filepath.write_text("\n".join(lines), encoding="utf-8")
    return filepath


def generate_aggregated_json(data: AggregatedReportData, filepath: Path) -> Path:
    payload = asdict(data)
    payload["generator"] = f"{APP_NAME} v{APP_VERSION}"
    filepath.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    return filepath


def generate_aggregated_xml(data: AggregatedReportData, filepath: Path) -> Path:
    root = ET.Element("ReconMasterJobReport", version=APP_VERSION)
    meta = ET.SubElement(root, "Meta")
    ET.SubElement(meta, "Target").text = data.target
    ET.SubElement(meta, "ScanStarted").text = data.scan_started
    ET.SubElement(meta, "ScanFinished").text = data.scan_finished
    ET.SubElement(meta, "Duration").text = data.duration

    sections_el = ET.SubElement(root, "Sections")
    for s in data.sections:
        sec_el = ET.SubElement(sections_el, "Section", index=str(s.index), status=s.status)
        ET.SubElement(sec_el, "Label").text = s.label
        ET.SubElement(sec_el, "Command").text = s.command
        ET.SubElement(sec_el, "Duration").text = s.duration
        ET.SubElement(sec_el, "Error").text = s.error
        ET.SubElement(sec_el, "Output").text = s.output
        if s.banners:
            banner_info_el = ET.SubElement(sec_el, "BannerInformation")
            for b in s.banners:
                b_el = ET.SubElement(banner_info_el, "Banner",
                                      port=str(b.get("port", "")),
                                      reachable=str(bool(b.get("reachable"))))
                b_el.text = b.get("banner") or ""

    notes_el = ET.SubElement(root, "Notes")
    for n in data.notes:
        ET.SubElement(notes_el, "Note").text = n

    summary_el = ET.SubElement(root, "Summary")
    for status, count in data.summary.items():
        ET.SubElement(summary_el, "Status", name=status).text = str(count)

    tree = ET.ElementTree(root)
    ET.indent(tree, space="  ")
    tree.write(filepath, encoding="utf-8", xml_declaration=True)
    return filepath


def generate_aggregated_html(data: AggregatedReportData, filepath: Path) -> Path:
    esc = html.escape
    sections_html = ""
    for s in data.sections:
        error_html = f"<p class='error'><b>Error:</b> {esc(s.error)}</p>" if s.error else ""
        banner_html = ""
        if s.banners:
            rows = "".join(
                f"<tr><td>{esc(str(b.get('port')))}</td>"
                f"<td>{'yes' if b.get('reachable') else 'no'}</td>"
                f"<td>{esc(b.get('banner') or '(no banner)')}</td></tr>"
                for b in s.banners
            )
            banner_html = f"""
      <h3>Banner Information</h3>
      <table><tr><th>Port</th><th>Reachable</th><th>Banner</th></tr>{rows}</table>"""
        sections_html += f"""
    <div class="section">
      <h2>[{s.index}] {esc(s.label)} — <span class="status status-{esc(s.status.lower())}">{esc(s.status)}</span></h2>
      <p><b>Command:</b> <code>{esc(s.command)}</code> &nbsp; <b>Duration:</b> {esc(s.duration)}</p>
      {error_html}
      <pre>{esc(s.output) or '(no output)'}</pre>
      {banner_html}
    </div>"""

    notes_html = "".join(f"<li>{esc(n)}</li>" for n in data.notes)
    summary_html = "".join(f"<li>{esc(status.title())}: {count}</li>" for status, count in data.summary.items())

    html_doc = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>{APP_NAME} Job Report — {esc(data.target)}</title>
<style>
  body {{ font-family: 'Segoe UI', Arial, sans-serif; background:#0d1117; color:#c9d1d9; margin:0; padding:2rem; }}
  h1 {{ color:#58a6ff; }}
  h2 {{ color:#79c0ff; border-bottom:1px solid #30363d; padding-bottom:.3rem; }}
  .section {{ margin-bottom:1.5rem; }}
  .status-completed {{ color:#3fb950; }}
  .status-failed, .status-timeout {{ color:#f85149; }}
  .status-skipped {{ color:#8b949e; }}
  pre {{ background:#161b22; padding:1rem; overflow-x:auto; border-radius:6px; max-height:400px; }}
  .error {{ color:#f85149; }}
  footer {{ margin-top:2rem; color:#8b949e; font-size:.85rem; }}
</style>
</head>
<body>
  <h1>{APP_NAME} — Job Report</h1>
  <p><b>Target:</b> {esc(data.target)} &nbsp; <b>Started:</b> {esc(data.scan_started)}
     &nbsp; <b>Finished:</b> {esc(data.scan_finished)} &nbsp; <b>Duration:</b> {esc(data.duration)}</p>
  {sections_html}
  <h2>Notes</h2>
  <ul>{notes_html or '<li>None</li>'}</ul>
  <h2>Summary</h2>
  <ul>{summary_html}</ul>
  <footer>Generated by {APP_NAME} v{APP_VERSION}</footer>
</body>
</html>"""
    filepath.write_text(html_doc, encoding="utf-8")
    return filepath


def generate_aggregated_pdf(data: AggregatedReportData, filepath: Path) -> Path:
    from xml.sax.saxutils import escape as xml_escape

    from reportlab.lib import colors
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import cm
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak

    esc = xml_escape
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle("Title2", parent=styles["Title"], textColor=colors.HexColor("#1f6feb"))
    heading_style = ParagraphStyle("Heading2b", parent=styles["Heading2"], textColor=colors.HexColor("#0d419d"))
    body_style = styles["BodyText"]
    mono_style = ParagraphStyle("Mono2", parent=styles["Code"], fontSize=8, leading=10)

    doc = SimpleDocTemplate(str(filepath), pagesize=A4, leftMargin=2 * cm, rightMargin=2 * cm,
                             topMargin=2 * cm, bottomMargin=2 * cm)
    story = [Paragraph(f"{APP_NAME} — Job Report", title_style), Spacer(1, 0.4 * cm)]
    story.append(Paragraph(f"<b>Target:</b> {esc(data.target)}", body_style))
    story.append(Paragraph(f"<b>Started:</b> {esc(data.scan_started)}", body_style))
    story.append(Paragraph(f"<b>Finished:</b> {esc(data.scan_finished)}", body_style))
    story.append(Paragraph(f"<b>Duration:</b> {esc(data.duration)}", body_style))
    story.append(Spacer(1, 0.4 * cm))

    for s in data.sections:
        story.append(Paragraph(f"[{s.index}] {esc(s.label)} — {esc(s.status)}", heading_style))
        story.append(Paragraph(f"<b>Command:</b> {esc(s.command)} &nbsp; <b>Duration:</b> {esc(s.duration)}", body_style))
        if s.error:
            story.append(Paragraph(f"<b>Error:</b> {esc(s.error)}", body_style))
        for line in (s.output or "(no output)").splitlines()[:200]:
            story.append(Paragraph(esc(line).replace(" ", "&nbsp;"), mono_style))
        if s.banners:
            story.append(Paragraph("Banner Information", ParagraphStyle(
                "SubHeading", parent=body_style, fontName="Helvetica-Bold", spaceBefore=6)))
            for b in s.banners:
                reach = "reachable" if b.get("reachable") else "unreachable"
                banner_text = esc(b.get("banner") or "(no banner)")
                story.append(Paragraph(f"Port {esc(str(b.get('port')))} [{reach}]: {banner_text}", mono_style))
        story.append(Spacer(1, 0.3 * cm))

    story.append(PageBreak())
    story.append(Paragraph("Notes", heading_style))
    for n in data.notes or ["None"]:
        story.append(Paragraph(f"• {esc(n)}", body_style))
    story.append(Paragraph("Summary", heading_style))
    for status, count in data.summary.items():
        story.append(Paragraph(f"{esc(status.title())}: {count}", body_style))
    story.append(Spacer(1, 0.5 * cm))
    story.append(Paragraph(f"Generated by {APP_NAME} v{APP_VERSION}", styles["Italic"]))

    doc.build(story)
    return filepath


_AGGREGATED_GENERATORS = {
    "txt": generate_aggregated_txt,
    "json": generate_aggregated_json,
    "xml": generate_aggregated_xml,
    "html": generate_aggregated_html,
    "pdf": generate_aggregated_pdf,
}


def generate_job_report(
    data: AggregatedReportData, fmt: str, filename: Optional[str] = None, out_dir: Path = REPORTS_DIR
) -> Path:
    """Generate a single aggregated-job report in the given format."""
    fmt = fmt.lower()
    if fmt not in _AGGREGATED_GENERATORS:
        raise ValueError(f"Unsupported report format: {fmt}")
    ensure_directory(out_dir)
    if filename:
        filename = sanitize_filename(filename)
    if not filename:
        filename = default_report_filename(data.target, fmt)
    if not filename.endswith(f".{fmt}"):
        filename = f"{filename}.{fmt}"
    filepath = out_dir / filename
    return _AGGREGATED_GENERATORS[fmt](data, filepath)


def generate_job_reports(
    data: AggregatedReportData, formats: List[str], base_filename: Optional[str] = None,
    out_dir: Path = REPORTS_DIR,
) -> List[Path]:
    """Generate every format the user selected from the same job data —
    Nmap is never re-run merely to produce a different report format."""
    paths = []
    for fmt in formats:
        name = f"{base_filename}.{fmt}" if base_filename else None
        paths.append(generate_job_report(data, fmt, name, out_dir))
    return paths


DEFAULT_RECOMMENDATIONS = [
    "Close or firewall any ports that are not required for business function.",
    "Keep exposed services patched and running supported versions.",
    "Disable verbose service banners where possible to reduce fingerprinting.",
    "Review NSE 'vuln' script findings promptly and validate manually before remediation.",
    "Restrict management ports (SSH, RDP, etc.) to trusted source addresses only.",
]


def build_report_data(
    scan_result: ScanResult,
    banners: Optional[List[Dict]] = None,
    nse_results: str = "",
    os_guess: str = "",
) -> ReportData:
    """Assemble a ReportData object from a raw ScanResult plus extras."""
    return ReportData(
        target=scan_result.target,
        date=human_timestamp(),
        duration=f"{scan_result.duration_seconds:.2f}s",
        command=" ".join(scan_result.command),
        open_ports=scan_result.open_ports,
        os_guess=os_guess,
        nse_results=nse_results,
        banners=banners or [],
        recommendations=DEFAULT_RECOMMENDATIONS,
        raw_output=scan_result.raw_output,
    )


# ---------------------------------------------------------------------------
# TXT
# ---------------------------------------------------------------------------

def generate_txt(data: ReportData, filepath: Path) -> Path:
    lines = [
        f"{APP_NAME} v{APP_VERSION} — Scan Report",
        "=" * 50,
        f"Target       : {data.target}",
        f"Date         : {data.date}",
        f"Duration     : {data.duration}",
        f"Command      : {data.command}",
        "",
        "Open Ports",
        "-" * 50,
    ]
    if data.open_ports:
        for p in data.open_ports:
            lines.append(f"  {p.get('port')}/{p.get('protocol', 'tcp')}  {p.get('service', '')}")
    else:
        lines.append("  (none parsed — see raw output below)")

    if data.os_guess:
        lines += ["", "Operating System", "-" * 50, f"  {data.os_guess}"]

    if data.nse_results:
        lines += ["", "NSE Script Results", "-" * 50, data.nse_results]

    if data.banners:
        lines += ["", "Banner Information", "-" * 50]
        for b in data.banners:
            lines.append(f"  {b.get('port')}: {b.get('banner') or '(no banner)'}")

    lines += ["", "Recommendations", "-" * 50]
    lines += [f"  - {r}" for r in data.recommendations]

    lines += ["", "Raw Nmap Output", "-" * 50, data.raw_output]
    lines += ["", "-" * 50, f"Generated by {APP_NAME} v{APP_VERSION}"]

    filepath.write_text("\n".join(lines), encoding="utf-8")
    return filepath


# ---------------------------------------------------------------------------
# JSON
# ---------------------------------------------------------------------------

def generate_json(data: ReportData, filepath: Path) -> Path:
    payload = asdict(data)
    payload["generator"] = f"{APP_NAME} v{APP_VERSION}"
    filepath.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    return filepath


# ---------------------------------------------------------------------------
# XML
# ---------------------------------------------------------------------------

def generate_xml(data: ReportData, filepath: Path) -> Path:
    root = ET.Element("ReconMasterReport", version=APP_VERSION)

    meta = ET.SubElement(root, "Meta")
    ET.SubElement(meta, "Target").text = data.target
    ET.SubElement(meta, "Date").text = data.date
    ET.SubElement(meta, "Duration").text = data.duration
    ET.SubElement(meta, "Command").text = data.command

    ports_el = ET.SubElement(root, "OpenPorts")
    for p in data.open_ports:
        port_el = ET.SubElement(ports_el, "Port")
        port_el.set("number", str(p.get("port", "")))
        port_el.set("protocol", str(p.get("protocol", "tcp")))
        port_el.text = str(p.get("service", ""))

    ET.SubElement(root, "OperatingSystem").text = data.os_guess
    ET.SubElement(root, "NSEResults").text = data.nse_results

    banners_el = ET.SubElement(root, "Banners")
    for b in data.banners:
        b_el = ET.SubElement(banners_el, "Banner")
        b_el.set("port", str(b.get("port", "")))
        b_el.text = b.get("banner") or ""

    rec_el = ET.SubElement(root, "Recommendations")
    for r in data.recommendations:
        ET.SubElement(rec_el, "Item").text = r

    ET.SubElement(root, "RawOutput").text = data.raw_output

    tree = ET.ElementTree(root)
    ET.indent(tree, space="  ")
    tree.write(filepath, encoding="utf-8", xml_declaration=True)
    return filepath


# ---------------------------------------------------------------------------
# HTML
# ---------------------------------------------------------------------------

def generate_html(data: ReportData, filepath: Path) -> Path:
    # Escape every piece of scan-derived or user-derived text before it is
    # interpolated into the HTML template. Nmap banners, service strings,
    # hostnames, and NSE output can legitimately contain '<', '>', or '&'
    # (e.g. a captured HTTP banner), which would otherwise break the page
    # structure or inject markup when the report is opened in a browser.
    esc = html.escape

    ports_rows = "".join(
        f"<tr><td>{esc(str(p.get('port')))}</td><td>{esc(p.get('protocol', 'tcp'))}</td>"
        f"<td>{esc(p.get('service', ''))}</td></tr>"
        for p in data.open_ports
    ) or "<tr><td colspan='3'>No parsed ports — see raw output</td></tr>"

    banner_rows = "".join(
        f"<tr><td>{esc(str(b.get('port')))}</td><td>{esc(b.get('banner') or '(no banner)')}</td></tr>"
        for b in data.banners
    ) or "<tr><td colspan='2'>No banners captured</td></tr>"

    rec_items = "".join(f"<li>{esc(r)}</li>" for r in data.recommendations)

    safe_target = esc(data.target)
    safe_date = esc(data.date)
    safe_duration = esc(data.duration)
    safe_command = esc(data.command)
    safe_os_guess = esc(data.os_guess) if data.os_guess else "Not detected / not requested"
    safe_nse = esc(data.nse_results) if data.nse_results else "No NSE scripts run"
    safe_raw = esc(data.raw_output)

    html_doc = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>{APP_NAME} Report — {safe_target}</title>
<style>
  body {{ font-family: 'Segoe UI', Arial, sans-serif; background:#0d1117; color:#c9d1d9; margin:0; padding:2rem; }}
  h1 {{ color:#58a6ff; }}
  h2 {{ color:#79c0ff; border-bottom:1px solid #30363d; padding-bottom:.3rem; }}
  table {{ width:100%; border-collapse:collapse; margin:1rem 0; }}
  th, td {{ border:1px solid #30363d; padding:.5rem; text-align:left; }}
  th {{ background:#161b22; }}
  .meta span {{ display:inline-block; margin-right:2rem; }}
  pre {{ background:#161b22; padding:1rem; overflow-x:auto; border-radius:6px; }}
  footer {{ margin-top:2rem; color:#8b949e; font-size:.85rem; }}
</style>
</head>
<body>
  <h1>{APP_NAME} — Scan Report</h1>
  <div class="meta">
    <span><b>Target:</b> {safe_target}</span>
    <span><b>Date:</b> {safe_date}</span>
    <span><b>Duration:</b> {safe_duration}</span>
  </div>
  <p><b>Command:</b> <code>{safe_command}</code></p>

  <h2>Open Ports</h2>
  <table><tr><th>Port</th><th>Protocol</th><th>Service</th></tr>{ports_rows}</table>

  <h2>Operating System</h2>
  <p>{safe_os_guess}</p>

  <h2>NSE Script Results</h2>
  <pre>{safe_nse}</pre>

  <h2>Banner Information</h2>
  <table><tr><th>Port</th><th>Banner</th></tr>{banner_rows}</table>

  <h2>Recommendations</h2>
  <ul>{rec_items}</ul>

  <h2>Raw Nmap Output</h2>
  <pre>{safe_raw}</pre>

  <footer>Generated by {APP_NAME} v{APP_VERSION}</footer>
</body>
</html>"""
    filepath.write_text(html_doc, encoding="utf-8")
    return filepath


# ---------------------------------------------------------------------------
# PDF (reportlab)
# ---------------------------------------------------------------------------

def generate_pdf(data: ReportData, filepath: Path) -> Path:
    from xml.sax.saxutils import escape as xml_escape

    from reportlab.lib import colors
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import cm
    from reportlab.platypus import (
        SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak,
    )

    # ReportLab's Paragraph() interprets a small XML-like markup subset
    # (<b>, <br/>, etc.), so any '<', '>', or '&' coming from real scan
    # data (HTTP banners, service strings, NSE output) must be escaped
    # first or Paragraph() raises a parse error and PDF generation fails.
    esc = xml_escape

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "TitleStyle", parent=styles["Title"], textColor=colors.HexColor("#1f6feb")
    )
    heading_style = ParagraphStyle(
        "HeadingStyle", parent=styles["Heading2"], textColor=colors.HexColor("#0d419d")
    )
    body_style = styles["BodyText"]
    mono_style = ParagraphStyle(
        "Mono", parent=styles["Code"], fontSize=8, leading=10
    )

    doc = SimpleDocTemplate(str(filepath), pagesize=A4,
                             leftMargin=2 * cm, rightMargin=2 * cm,
                             topMargin=2 * cm, bottomMargin=2 * cm)
    story = []

    story.append(Paragraph(f"{APP_NAME} — Scan Report", title_style))
    story.append(Spacer(1, 0.5 * cm))
    story.append(Paragraph(f"<b>Target:</b> {esc(data.target)}", body_style))
    story.append(Paragraph(f"<b>Date:</b> {esc(data.date)}", body_style))
    story.append(Paragraph(f"<b>Duration:</b> {esc(data.duration)}", body_style))
    story.append(Paragraph(f"<b>Command:</b> {esc(data.command)}", body_style))
    story.append(Spacer(1, 0.5 * cm))

    story.append(Paragraph("Open Ports", heading_style))
    table_data = [["Port", "Protocol", "Service"]]
    if data.open_ports:
        for p in data.open_ports:
            table_data.append([
                str(p.get("port")), esc(p.get("protocol", "tcp")), esc(p.get("service", "")),
            ])
    else:
        table_data.append(["-", "-", "See raw output"])
    tbl = Table(table_data, colWidths=[3 * cm, 3 * cm, 8 * cm])
    tbl.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1f6feb")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
    ]))
    story.append(tbl)
    story.append(Spacer(1, 0.4 * cm))

    story.append(Paragraph("Operating System", heading_style))
    story.append(Paragraph(esc(data.os_guess) or "Not detected / not requested", body_style))

    story.append(Paragraph("NSE Script Results", heading_style))
    nse_text = esc(data.nse_results) if data.nse_results else "No NSE scripts run"
    story.append(Paragraph(nse_text.replace("\n", "<br/>"), mono_style))

    story.append(Paragraph("Banner Information", heading_style))
    banner_table = [["Port", "Banner"]]
    if data.banners:
        for b in data.banners:
            banner_text = esc((b.get("banner") or "(no banner)")[:80])
            banner_table.append([str(b.get("port")), banner_text])
    else:
        banner_table.append(["-", "No banners captured"])
    btbl = Table(banner_table, colWidths=[3 * cm, 11 * cm])
    btbl.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1f6feb")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
    ]))
    story.append(btbl)
    story.append(Spacer(1, 0.4 * cm))

    story.append(Paragraph("Recommendations", heading_style))
    for r in data.recommendations:
        story.append(Paragraph(f"• {r}", body_style))

    story.append(PageBreak())
    story.append(Paragraph("Raw Nmap Output", heading_style))
    for line in data.raw_output.splitlines() or ["(no output)"]:
        story.append(Paragraph(esc(line).replace(" ", "&nbsp;"), mono_style))

    story.append(Spacer(1, 1 * cm))
    story.append(Paragraph(f"Generated by {APP_NAME} v{APP_VERSION}", styles["Italic"]))

    doc.build(story)
    return filepath


# ---------------------------------------------------------------------------
# Dispatcher
# ---------------------------------------------------------------------------

_GENERATORS = {
    "txt": generate_txt,
    "json": generate_json,
    "xml": generate_xml,
    "html": generate_html,
    "pdf": generate_pdf,
}


def generate_report(
    data: ReportData, fmt: str, filename: Optional[str] = None, out_dir: Path = REPORTS_DIR
) -> Path:
    """
    Generate a single report in the given format ('txt'|'json'|'xml'|'html'|'pdf').
    Returns the path to the written file.
    """
    fmt = fmt.lower()
    if fmt not in _GENERATORS:
        raise ValueError(f"Unsupported report format: {fmt}")

    ensure_directory(out_dir)

    if filename:
        # Strip any directory components / traversal sequences the user
        # may have entered ('../', an absolute path, etc.) so the report
        # can never be written outside out_dir.
        filename = sanitize_filename(filename)

    if not filename:
        filename = default_report_filename(data.target, fmt)
    if not filename.endswith(f".{fmt}"):
        filename = f"{filename}.{fmt}"

    filepath = out_dir / filename
    return _GENERATORS[fmt](data, filepath)


def generate_all_formats(
    data: ReportData, base_filename: Optional[str] = None, out_dir: Path = REPORTS_DIR
) -> List[Path]:
    """Generate every supported report format for the same scan data."""
    paths = []
    for fmt in _GENERATORS:
        name = f"{base_filename}.{fmt}" if base_filename else None
        paths.append(generate_report(data, fmt, name, out_dir))
    return paths
